### PR TITLE
WiP: An attept to reduce the certificate permissions

### LINKED ISSUE #259: Wrong ACL for certificates
This is the second problem that broke the build. I am working on a fix that should make the certificates ACLs more secure.
I will push on dev asap.

### PR DESCRIPTION
**Pull request by arodier**
The certificates should be readable only by their counterparts
programs, for instance, imap / pop3 by dovecot, smtp by postfix,
etc...

This should fix #259

### CODE REVIEW

File: install/playbooks/roles/certificates/files/renewal-hook.sh [hunk 1]
```diff
@@ -16,10 +16,12 @@ for fqdn in $RENEWED_DOMAINS; do
         restart_nginx=$(grep -Rl "server_name $fqdn" /etc/nginx/sites-enabled/ | grep -v -e -cert -c)
     fi
 
+    # Make sure the full chain is readable by all programs
+    chmod a+r /etc/letsencrypt/archive/$fqdn/fullchain*.pem
```
Comment (arodier) [inline install/playbooks/roles/certificates/files/renewal-hook.sh]: I am not sure yet why I needed to do this to have LDAP authentication working with Dovecot.
It seems dovecot and postfix need to read the fullchain in the ldap folder.

File: install/playbooks/roles/dovecot/templates/dovecot-ldap.conf.ext [hunk 2]
```diff
@@ -41,8 +41,10 @@ dnpass = {{ lookup("password", ldap.roPasswdParams) }}
 # dn is still the logged in user. Normally you want to keep this empty.
 #sasl_authz_id =
 
-# Use TLS to connect to the LDAP server.
-tls = yes
+# Use TLS to connect to the LDAP server is not necessary,
+# as it is on the same server. Putting yes here also seems to require
+# additional permissions for certificates sharing by dovecot.
+tls = no
```
Comment (fredericmoulins) [inline install/playbooks/roles/dovecot/templates/dovecot-ldap.conf.ext]: Apparently, you already dealt with that in the past since the apparmor profile for `usr.lib.dovecot.auth` includes the ldap certificate:
```
$ git grep 'letsencrypt' install/playbooks/roles/dovecot/templates/apparmor.d/
install/playbooks/roles/dovecot/templates/apparmor.d/local/usr.lib.dovecot.auth:  /etc/letsencrypt/archive/ldap.{{ network.domain }}/* r,
install/playbooks/roles/dovecot/templates/apparmor.d/local/usr.lib.dovecot.config:  /etc/letsencrypt/archive/imap.{{ network.domain }}/* r,
install/playbooks/roles/dovecot/templates/apparmor.d/local/usr.lib.dovecot.config:  /etc/letsencrypt/archive/pop3.{{ network.domain }}/* r,
install/playbooks/roles/dovecot/templates/apparmor.d/local/usr.sbin.dovecot:  /etc/letsencrypt/archive/imap.{{ network.domain }}/* r,
install/playbooks/roles/dovecot/templates/apparmor.d/local/usr.sbin.dovecot:  /etc/letsencrypt/archive/pop3.{{ network.domain }}/* r,
```
Any idea why you would have activated TLS then?

File: install/playbooks/roles/ldap/vars/main.yml [hunk 3]
```diff
@@ -5,3 +5,19 @@ users_defaults:
...
+    - python-ldap
+    - python-passlib
+    - ldapscripts
+    - libpam-pwquality
+    - ldapvi
+    - nscd
+  remove:
+    - libpam-cracklib
+    - cracklib-runtime
+    - libcrack2
```
Comment (fredericmoulins) [inline install/playbooks/roles/ldap/vars/main.yml]: `libcrack2` seems to be a dependency of `libpam-pwquality` via `libpwquality1`, better not try to remove it. 

So `cracklib-runtime` gets removed. it was installed before. It is not used?

Do you know by what dependency `libpam-cracklib` got installed? I don't have it here, but it is a build from before the changes tested by the CI.

File: install/playbooks/roles/system-post-install/tasks/partitions-security.yml [hunk 4]
```diff
@@ -4,6 +4,8 @@
 - name: Check if /tmp is a mount point
```
Comment (fredericmoulins) [inline install/playbooks/roles/system-post-install/tasks/partitions-security.yml]: Unrelated?

File: common/roles/cert-perms/tasks/main.yml [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+    group: '{{ entity_group }}'
+    recurse: true
+  with_items:
+      - '/etc/letsencrypt/archive/{{ cert_dir }}'
+      - '/etc/letsencrypt/live/{{ cert_dir }}'
+  loop_control:
+    loop_var: path
+
+# This one sets the g+s flag, meaning that any new certificate created
+# will belongs to the group of its parent
```
[the remark this answers is not in the document]
Comment (arodier) [reply common/roles/cert-perms/tasks/main.yml]: > Why not use the ACLs?
The annoying thing about the ACL is the "default" flag (e.g. -r-) and the executable flag of the directory.

> Maybe right now the default ACLs are set too high in the hierarchy.
Yes, this is why I tried to dig into the lower directory, per subdomain.

This is a work in progress, to see if I can reach something simple but secure. If I fail, I may go back to the way it was before.

File: install/playbooks/roles/system-post-install/tasks/partitions-security.yml (hunk 4 above)
Comment (arodier) [reply install/playbooks/roles/system-post-install/tasks/partitions-security.yml]: Yes, definitely, I will remove it from there.

File: install/playbooks/roles/ldap/vars/main.yml (hunk 3 above)
Comment (arodier) [reply install/playbooks/roles/ldap/vars/main.yml]: The LDAP server fail to start if both libraries are used. Maybe a recent update in Debian that pushed libpam-cracklib in the default packages to install?.
This is minor, and more related to #258.

File: install/playbooks/roles/dovecot/templates/dovecot-ldap.conf.ext (hunk 2 above)
Comment (arodier) [reply install/playbooks/roles/dovecot/templates/dovecot-ldap.conf.ext]: I don't understand why the dovecot need to access the LDAP certificate to establish a TLS connection.

File: install/playbooks/roles/ldap/vars/main.yml (hunk 3 above)
Comment (arodier) [reply install/playbooks/roles/ldap/vars/main.yml]: I followed your advice on this one, done.

**Comment by arodier** [comment]
The last one, based on ACL, in the file common/roles/cert-perms/tasks/main.yml works perfectly, although a little bit complex. One thing I noticed: using chmod on the files or directory, _after_ using ACL seems to mess up the "effective" acl.

Otherwise, the result:

```
root@hmbx:/etc/letsencrypt/archive# getfacl ldap.hmbx.pw/
# file: ldap.hmbx.pw/
# owner: root
# group: root
user::rwx
user:www-data:r-x
user:openldap:r-x
group::---
mask::r-x
other::---
default:user::rwx
default:user:openldap:r--
default:group::---
default:mask::r-x
default:other::---
```

An existing file in the directory:

```
root@hmbx:/etc/letsencrypt/archive# getfacl ldap.hmbx.pw/fullchain1.pem 
# file: ldap.hmbx.pw/fullchain1.pem
# owner: root
# group: root
user::rw-
user:openldap:r--
group::---
mask::r--
other::---
```

A new file created in the directory:

```
root@hmbx:/etc/letsencrypt/archive# touch ldap.hmbx.pw/test
root@hmbx:/etc/letsencrypt/archive# getfacl ldap.hmbx.pw/test 
# file: ldap.hmbx.pw/test
# owner: root
# group: root
user::rw-
user:openldap:r--
group::---
mask::r--
other::---
```

It seems solid to me. Once it is finished, let's see the pros and cons

**Comment by arodier** [comment]
And now, the TLS option works again for dovecot, and all the tests are passing.

It is not perfect and can be simplified in a second commit, for instance by using the find module of Ansible to set the ACL on the certificates already present.

However, I like the fact that the permissions are restricted to root with additional selective ACLs for the relevant daemons.

File: install/playbooks/roles/system-post-install/tasks/partitions-security.yml (hunk 4 above)
Comment (arodier) [reply install/playbooks/roles/system-post-install/tasks/partitions-security.yml]: It is a fix as it was failing when /tmp was not a mounting point.
We can remove this and place it in another branch, if you want.

Comment (fredericmoulins) [reply install/playbooks/roles/system-post-install/tasks/partitions-security.yml]: Ok, I see. At least in a separate commit, it would be ok for me.

File: install/playbooks/roles/dovecot/tasks/main.yml [hunk 6]
```diff
@@ -31,22 +31,31 @@
...
+
+- name: Set the variables for the certificate
+  when: mail.pop3
+  set_fact:
+    cert_dir: 'pop3.{{ network.domain }}'
+    entity_group: dovecot
+
+- name: Set the default permissions for the pop3 certificate folders
+  when: mail.pop3
+  include_tasks: '{{ playbook_dir }}/../../common/roles/cert-perms/tasks/main.yml'
```
Comment (fredericmoulins) [inline install/playbooks/roles/dovecot/tasks/main.yml]: Ha, ok, in the dovecot main tasks, the permissions will be set, assuming that the certificates are already generated by certbot. So, the directories are already created with the permissions set by certbot.

The certificates for dovecot are generated in separate playbooks and there is no dependency relationship between those playbooks and roles. Maybe this could be refactored in the future. (Integrated in the certificates role? Just looking at it, I am not sure of the implications)

But it seems quite some changes… If it works like that, it looks like better version of the current rights/ACL setup, so that's good enough for me for now.

File: install/playbooks/roles/certificates/tasks/main.yml [hunk 7]
```diff
@@ -127,6 +127,38 @@
   when: is_valid.stdout == "0"
   include_tasks: gencert.yml
 
+- name: Restrict permissions for the root of LetsEncrypt certificate directory
+  file:
+    path: '{{ path.location }}'
+    state: directory
+    mode: '{{ path.mode | default("0755") }}'
```
[the remark this answers is not in the document]
Comment (arodier) [reply install/playbooks/roles/certificates/tasks/main.yml]: > The recursion should take care of the files already present, right?

Yes, this was the point of the recursion. When you restore your certificates (dev or live), the permissions needed to be set.

> On my system, the archive and live directories are 750

Perhaps this is needed if the group is different. It does not hurt to do it, thought. I think there is a dedicated group (ssl-cert) on Debian. The approach certbot may take in the future is to make sure these certificates belongs to these groups. We will see in buster.

File: install/playbooks/roles/dovecot/tasks/main.yml (hunk 6 above)
Comment (arodier) [reply install/playbooks/roles/dovecot/tasks/main.yml]: I thought about adding the permissions in the certificate roles, this would be indeed the cleanest way, unfortunately, the user that need access to the certificates is not existing yet!

However, I agree some refactoring is needed.

Thanks for the feedback
